# - name: Set site name without test suffix for default host.
  # set_fact:
    # httpd_site_name: "{{ site_name }}"
  # when: site_name == '000-default'

- name: Add .local suffix to httpd_site_name if needed.
  set_fact:
    httpd_site_name: "{{ httpd_site_name ~ local_test_environment|default('') }}"
  when: httpd_site_name != 'default'



- name: Install snippet for avahi config if in test environment.
  template: src=avahi_aliases.j2 dest={{AVAHI_ALIASES_CONFIG_DIR}}/{{httpd_site_name}}
  when: local_test_environment is defined and httpd_site_avahi_alias and
        httpd_site_name != 'default'
  notify:
    - restart avahi-alias
